@baseurl=http://localhost:5656
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ5MzEzNjM3LCJleHAiOjE3NDk0MDAwMzd9.rgRlhlY-NzJA6ZZaFcv7QAFKv2VzaVfl0BMplB2iTTQ

###
GET {{baseurl}}/auth/getUser
Authorization: Bearer {{token}}



### get scholarship data
GET http://localhost:5656/scholarships

###get by applying filters
GET http://localhost:5656/scholarshipfilter?country=Singapore&university=Nanyang%20Technological%20University%20(NTU)&degree=PhD

###for bookmarks
POST http://localhost:5656/auth/bookmark
Content-Type:application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzQ3Njc1MTUwLCJleHAiOjE3NDc3NjE1NTB9.Ef-6Cwgd4S_cy77dfbQHqwWncEK0KgcgThu2YPNOewU

{
    "bookmark_id":1
}

###
POST http://localhost:5656/auth/login
Content-Type: application/json

{
    "email":"b@b.com",
    "password":"1234"
}

###
GET http://localhost:5656/dashboard

###get scholarship single ones info
GET http://localhost:5656/scholarshiplist/1


###
DELETE http://localhost:5656/auth/remove
Content-Type:application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzQ3Njc1MTUwLCJleHAiOjE3NDc3NjE1NTB9.Ef-6Cwgd4S_cy77dfbQHqwWncEK0KgcgThu2YPNOewU

{
    "userdata_id":3,
    "bookmark_id":2
}